# The host for your Gover instance.
Host: my.domain.de


# Settings for the ingress.
Ingress:
    # Disable it if you want to use your own ingress or another reverse proxy.
    # Options are true or false.
    Enabled: true
    # Max body size for requests.
    # Must be big enough for file uploads from citizens.
    MaxBodySize: 16M


# Settings for the Let's Encrypt SSL resolution.
LetsEncrypt:
    # Disable it if you want to use your own SSL certificate.
    # Options are true or false.
    Enabled: true
    # The mail address for Let's Encrypt notifications.
    ContactMail: mail@my.domain.de
    # The environment mode for Let's Encrypt.
    # Options are production or staging.
    Mode: production


# Settings for the Gover application
Gover:
    # The mail address where error mails are sent to.
    # This will be used if no sentry is set up.
    ReportMail: admin@my.domain.de

    # Set the telemetry key for the Gover application.
    # This is used to fetch telemetry data from the Gover application.
    # This is especially useful if you have multiple instances of the Gover application running.
    TelemetryKey: 'some-telemetry-key'

    # Settings for the database connection.
    Database:
        # The host for the Gover database.
        Host: gover-database.my.domain.de
        # The port for the Gover database.
        Port: 5432
        # The username for the Gover database.
        Username: gover
        # The password for the Gover database.
        Password: gover
        # The name of the Gover database.
        Database: gover

    # Settings for the SMTP connection and mail sending in general.
    Smtp:
        # The mail address for the sender of the mails.
        FromMail: '"Gover" <noreply@my.domain.de>'
        # The host for the SMTP server.
        Host: smtp.my.domain.de
        # The port for the SMTP server.
        Port: 587
        # The username for the SMTP server.
        # Set this to an empty string (''), if no authentication is required.
        Username: username
        # The password for the SMTP server.
        # Set this to an empty string (''), if no authentication is required.
        Password: password
        # The authentication mode for the SMTP server.
        # Options are true or false.
        # Set this to false, if no authentication in required.
        DisableAuth: false
        # The TLS mode for the SMTP server.
        # Options are true or false.
        DisableTLS: false

    # Set the Sentry config for the Gover application.
    # This is used to send error reports to Sentry.
    # Remove this section if you don't want to use Sentry.
    Sentry:
        # The environment for the Sentry instance.
        Environment: development
        # The DSN for the Sentry instance where errors from the server will be reported.
        Server: https://123@sentry.my.domain.de/1
        # The DSN for the Sentry instance where errors from the web-app will be reported.
        App: https://789@sentry.my.domain.de/2

    # Settings for file uploads for citizens.
    # These are the most common file extensions and content types as an example.
    # Limit or extend these lists as needed.
    Files:
        # List of allowed file extensions.
        Extensions: |
            pdf, png, jpg, jpeg, doc, docx, xls, xlsx, ppt, pptx, odt, fodt, ods, fods, odp, fodp, odg, fodg, odf
        # List of allowed file content types.
        ContentTypes: |
            application/pdf, image/png, image/jpeg, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/msexcel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/mspowerpoint, application/vnd.openxmlformats-officedocument.presentationml.presentation, application/vnd.oasis.opendocument.text, application/vnd.oasis.opendocument.spreadsheet, application/vnd.oasis.opendocument.presentation, application/vnd.oasis.opendocument.graphics, application/vnd.oasis.opendocument.formula

    # Settings for the payment providers.
    # Remove this section if you don't want to use any of them.
    Payment:
        # Settings for the EPayBL payment provider.
        # If you want to use EPayBL, you need to set up the certificate in the Gover application.
        # Place the certificate in the files folder of this cart with the name epaybl.p12.
        # Remove this section if you don't want to use EPayBL.
        EPayBL:
            # The URL for the EPayBL payment provider.
            # Set this to production URL if you want to use the production environment.
            Url: https://epayment-stage.dataport.de/konnektor/epayment/
            # The base64 encoded certificate for the ePayBL provider.
            CertBase64: {{ .Files.Get "files/epaybl.p12" | b64enc }}
            # The password for the ePayBL certificate.
            CertPassword: password

        # Settings for the pmPayment provider.
        # Remove this section if you don't want to use pmPayment.
        PmPayment:
            # The URL for the pmPayment provider.
            # Set this to production URL if you want to use the production environment.
            # URL must end with a slash
            Url: https://payment-test.govconnect.de/
            # The client id for the pmPayment provider.
            # You can get this from the portal of pmPayment in the oAuth-Section.
            ClientId: clientid
            # The client secret for the pmPayment provider.
            # You can get this from the portal of pmPayment in the oAuth-Section.
            ClientSecret: clientsecret

        # Settings for the Giropay payment provider.
        # Remove this section if you don't want to use Giropay.
        Giropay:
            # The URL for the Giropay payment provider.
            # This is production and staging in one.
            Url: https://payment.girosolution.de/girocheckout/api/v2/transaction/start
            # The password for giropay.
            # You can get this from the giropay portal.
            ProjectPassword: password

    # Settings for the storage connection.
    Storage:
        # The host for the S3 storage.
        Endpoint: https://storage.my.domain.de
        # The access key for the S3 storage.
        AccessKey: accesskey
        # The secret key for the S3 storage.
        SecretKey: secretkey
        # The bucket for the S3 storage.
        Bucket: gover

    # Settings for the ClamAV connection.
    ClamAV:
        # The host for the ClamAV instance.
        Host: clamav.my.domain.de
        # The port for the ClamAV instance.
        Port: 3310


# Settings for the Keycloak instance.
Keycloak:
    # Initial username for the keycloak admin user.
    # You should change this when keycloak is running.
    Username: admin
    # Initial password for the keycloak admin user.
    # You should change this when keycloak is running.
    Password: admin
    # The secret for the Gover backend client to connect to Keycloak.
    GoverBackendClientSecret: secret

    # Settings for the database connection.
    Database:
        # The host for the Keycloak database.
        Host: keycloak-database.my.domain.de
        # The port for the Keycloak database.
        Port: 5432
        # The username for the Keycloak database.
        Username: gover
        # The password for the Keycloak database.
        Password: gover
        # The name of the Keycloak database.
        Database: gover

    # Settings for the identity provider data when using Keycloak.
    IdProviderData:
        # Name of the service connecting to the various identity providers.
        # This should usually be Gover.
        Name: Gover
        # Display name of the provider of the Gover instance.
        # This will be shown to the citizens when they use the identity providers.
        DisplayName: Gover Testinstanz
        # Description of the provider of the Gover instance.
        # This will be shown to the citizens when they use the identity providers.
        Description: Testinstanz von Gover
        # Data of the organization running the Gover instance.
        Org:
            # Name of the organization running the Gover instance.
            Name: Musterstadt
            # URL of the organization running the Gover instance.
            Url: https://musterstadt.de
        # Technical contact data of the organization running the Gover instance.
        TechnicalContact:
            Name: Max Mustermann
            Email: technik@musterstadt.de
        # Support contact data of the organization running the Gover instance.
        SupportContact:
            Name: Erika Musterfrau
            Email: hilfe@musterstadt.de
