-   name: Pull Postgres Docker image
    community.docker.docker_image:
        name: "{{ image }}"
        source: pull

-   name: Create postgres container
    community.docker.docker_container:
        name: postgres
        image: "{{ image }}"
        restart_policy: always
        published_ports:
            - "5432:5432"
        env:
            POSTGRES_USER: "{{ admin_username }}"
            POSTGRES_PASSWORD: "{{ admin_password }}"
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - "/mnt/pgdata:/var/lib/postgresql/data"
        state: started