apiVersion: apps/v1
kind: Deployment
metadata:
  name: gover-staff-app-deployment
  labels:
    app: gover-staff-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gover-staff-app
  template:
    metadata:
      labels:
        app: gover-staff-app
    spec:
      containers:
        - name: gover-staff-app
          image: ghcr.io/aivot-digital/gover:4.2.5
          ports:
            - containerPort: 80
          args:
            - staff
---
apiVersion: v1
kind: Service
metadata:
  name: gover-staff-app-service
  labels:
    app: gover-staff-app-service
spec:
  type: ClusterIP
  selector:
    app: gover-staff-app
  ports:
    - protocol: TCP
      port: 80