{{- if .Values.Ingress.Enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gover-ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt-{{ .Values.LetsEncrypt.Mode }}"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.Host }}
      secretName: "gover-{{ .Release.Namespace }}-{{ .Values.LetsEncrypt.Mode }}-tls"
  rules:
    - host: {{ .Values.Host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gover-service
                port:
                  number: 8080
          - path: /idp
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  number: 8080
          - path: /staff
            pathType: Prefix
            backend:
              service:
                name: gover-staff-app-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gover-customer-app-service
                port:
                  number: 80
{{- end }}